#!/bin/bash

# Identifying the system package manager

if [ -e /usr/bin/apt ]; then
	packagemanager=apt
	echo -e "\e[32mPackage manager: $packagemanager\e[0m" 
elif [ -e /usr/bin/dnf ]; then
	packagemanager=dnf
	echo -e "\e[32mPackage manager: $packagemanager\e[0m" 
elif [ -e /usr/bin/yum ]; then
	packagemanager=yum
	echo -e "\e[32mPackage manager: $packagemanager\e[0m" 
else 
	echo "Package manager not found. This script only support apt, yum and dnf.";
    		exit 1
fi

# Updating package list
if $packagemanager=apt; then
    sudo apt update 
elif $packagemanager=yum; then
    sudo yum check-update
elif $packagemanager=dnf; then
    sudo dnf check-update
fi



# Checking prerequisites to nativefy WhatsApp
echo -e "\e[30;42mChecking prerequisites to nativefy WhatsApp\e[0m"

# Installing Nodejs and NPM

if [ -e /usr/bin/nodejs ] ; [ -e /usr/bin/npm ]; then
	nodejsversion=$(nodejs -v | tr -dc '0-9, .'| head -c 2)
	npmversion=$(npm -v | head -c 1)
		if (($nodejsversion>=13)) && (($npmversion>=7)); then
			echo -e "\e[32mNodejs and NPM is installed, Nodejs version is `nodejs -v` and NPM version is `npm -v`, compatible with Nativefier\e[0m"
		elif (($nodejsversion<13)) ; (($npmversion<7)); then
        		echo -e "\e[32mNodejs and NPM is installed, Nodejs version is `nodejs -v` and NPM version is `npm -v`, both not compatible with Nativefier, updating ...\e[0m"       
           		if packagemanager=apt; then 
                		curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash - 
           		else 
                		curl -fsSL https://rpm.nodesource.com/setup_16.x | sudo bash -
           		fi
		elif (($nodejsversion>=13)) ; (($npmversion<7)); then
        		echo -e "\e[32mNodejs and NPM is installed, Nodejs version is `nodejs -v` and NPM version is `npm -v`, NPM not compatible with Nativefier, updating ...\e[0m"       
           		if packagemanager=apt; then 
                		curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash - 
           		else 
                		curl -fsSL https://rpm.nodesource.com/setup_16.x | sudo bash -
           		fi
		elif (($nodejsversion<13)) ; (($npmversion>=7)); then
        		echo -e "\e[32mNodejs and NPM is installed, Nodejs version is `nodejs -v` and NPM version is `npm -v`, Nodejs not compatible with Nativefier, updating ...\e[0m"       
           		if packagemanager=apt; then 
                		curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash - 
           		else 
                		curl -fsSL https://rpm.nodesource.com/setup_16.x | sudo bash -
           		fi
		fi
else
	echo -e "\e[32mInstalling Nodejs and NPM for you... \e[0m"
            if packagemanager=apt; then 
                curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
            else 
                curl -fsSL https://rpm.nodesource.com/setup_16.x | sudo bash -
            fi
fi

# Installing Nativefier
if [ -e 
npm install -g nativefier
sudo mkdir WhatsApp
cd Whatsapp
wget https://raw.githubusercontent.com/ITdairy/whatsapp-nativefier-script/main/run-whatsapp.sh
wget https://raw.githubusercontent.com/ITdairy/whatsapp-nativefier-script/main/whatsapp.desktop
 
#Nativefier WhatsApp with user agent
echo -e '\e[32mNativefying WhatsApp from http://web.whatsapp.com ...\e[39m'
nativefier https://web.whatsapp.com --user-agent "Mozilla/5.0 (X11; CrOS armv7l 13597.84.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.187 Safari/537.36" -a `uname -m` --maximize -n WhatsApp
cd ./WhatsApp-linux-`uname -m`
sudo cp ../run-whatsapp.sh ./
sudo chmod +x ./run-whatsapp.sh
cd ..
echo -e '\e[32mDone installing WhatsApp, Creating desktop shortcut and menu shortcut...'

#Create desktop & menu shortcut
sudo cp ./whatsapp.desktop /usr/share/applications
sudo cp ./whatsapp.desktop ~/Desktop
echo -e '\e[32mDone! You can now run WhatsApp from desktop and menu bar.\e[39m'
echo -e "\e[101mPlease let me know if you can't see desktop shortcut and menu bar shortcut!\e[0m"
cd ~/

