#!/usr/bin/env bash

# Identifying the system package manager
if command -v apt > /dev/null; then
    packagemanager=apt
    echo -e "\\e[32mPackage manager is $packagemanager\\e[0m"
    sudo $packagemanager install wget curl -y
elif command -v dnf > /dev/null; then
    packagemanager=dnf
    echo -e "\\e[32mPackage manager is $packagemanager\\e[0m"
    sudo $packagemanager install wget curl -y
elif command -v yum > /dev/null; then
    packagemanager=yum
    echo -e "\\e[32mPackage manager is $packagemanager\\e[0m"
    sudo $packagemanager install wget curl -y
else
    echo -e "\\e[41;5mPackage manager not found. This script only support apt, yum and dnf.\\e[0m";
    exit 1
fi


# Installing Nodejs and NPM
if [ $packagemanager == 'apt' ]; then
    echo -e "\\e[32mAdding NodeSource...\\e[0m"
    curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash - > /dev/null
    echo -e "\\e[32mRunning sudo apt update and sudo apt install nodejs -y...\\e[0m"
    sudo apt update > /dev/null
    sudo apt install nodejs -y > /dev/null
else
    echo -e "\\e[32mAdding NodeSource...\\e[0m"
    curl -fsSL https://rpm.nodesource.com/setup_16.x | sudo bash - > /dev/null
    echo -e "\\e[32mRunning sudo $packagemanager check-update and sudo $packagemanager install nodejs -y...\\e[0m"
    sudo $packagemanager check-update > /dev/null
    sudo $packagemanager install nodejs -y > /dev/null
fi


# Installing Nativefier
if command -v npm > /dev/null; then
    npm install -g nativefier || exit 1 
    sudo mkdir "${HOME}/WhatsApp" || exit 1
    cd "${HOME}/WhatsApp" || exit 1
    wget -qo- https://raw.githubusercontent.com/ITdairy/whatsapp-for-linux/main/run-whatsapp.sh || exit 1 
    wget -qo- https://raw.githubusercontent.com/ITdairy/whatsapp-for-linux/main/whatsapp.desktop || exit 1 
    wget -qo- https://github.com/ITdairy/whatsapp-for-linux/raw/main/whatsapp.png || exit 1 
else
    echo -e "\\e[41;5mFailed. NPM not found.\\e[0m"
    exit 1
fi


#Nativefying WhatsApp
if command -v nativefier > /dev/null; then
    echo -e '\\e[32mNativefying WhatsApp from http://web.whatsapp.com ...\\e[39m'
    nativefier https://web.whatsapp.com --user-agent "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36" -a "$(uname -m)" --maximize -n WhatsApp > /dev/null
    sudo touch run-whatsapp
    echo "sudo rm -rf ${HOME}/.config/whatsapp-nativefier-*/Service Worker && $HOME/WhatsApp/WhatsApp-linux-$(uname -m)/WhatsApp" > ./run-whatsapp
    sudo chmod +x ./run-whatsapp
    echo -e '\\e[32mDone installing WhatsApp, Creating desktop shortcut and menu shortcut...'
else
    echo -e "\\e[41;5mFailed. Nativefier not found.\\e[0m"
    exit 1
fi


#Create desktop & menu shortcut
sudo cp ./whatsapp.desktop "$HOME/.local/share/applications"
sudo cp ./whatsapp.desktop "$HOME/Desktop"
echo -e '\\e[32mDone! You should be able to run WhatsApp from desktop and menu bar.\\e[39m'
cd "$HOME"  || exit 0
